# This is the workflow to lint the source code
name: Cancel Workflow

# Controls when the action will run.
on:
  # Allows you to call this workflow from other workflows
  workflow_call:

jobs:
  cancel-runs:
    name: '🛑 Cancel Previous Runs'
    runs-on: [self-hosted, linux]

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
