# This is workflow runs on push
#
name: Release

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  push:
    branches: [main, next, beta, alpha]

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-code:
    name: '▶️ actions'
    uses: ./.github/workflows/lint-code.yml

    # Test is currently covered by test-code
  # build-code:
  #   name: '▶️ actions'
  #   needs: [lint-code]
  #   uses: ./.github/workflows/build-code.yml

  test-code:
    name: '▶️ actions'
    uses: ./.github/workflows/test-code.yml

  # visual-test:
  #   name: '▶️ actions'
  #   # execute after successful code validation to save unnecessary screenshots costs
  #   needs: [lint-code, build-code, test-code, codeql, sonarqube]
  #   if: github.event.pull_request.draft == false # do not run on draft PR
  #   uses: ./.github/workflows/visual-test.yml
  #   secrets:
  #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN  }}

  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    name: '▶️ actions'
    needs: [lint-code, test-code]
    uses: ./.github/workflows/release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}

  publish:
    permissions:
      contents: read
      deployments: write

    name: '▶️ actions'
    needs: [release]
    uses: ./.github/workflows/publish.yml
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN  }}
      CLOUDFLARE_ID: ${{ secrets.CLOUDFLARE_ID  }}
