name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    container: node:lts-buster

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get Git history for the changelog

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci --no-optional --no-audit --prefer-offline --progress=false

      - name: Run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
